### ISSUE TITLE
OpenWRT Mipsle Error

### ISSUE THREAD

**Issue by Dvineone** [notsure2/cake-autorate#2]
Hi,
I am getting the below error when trying to run on OpenWrt. Any idea why this error would be occuring?

Error: /cake-autorate-linux-mipsle-0.4: line 1: syntax error: unexpected "("

OS-Version
  NAME="EZR23"
  VERSION="EV3124"
  ID="ezr23"
  ID_LIKE="lede openwrt"
  PRETTY_NAME="EZR23 EV3124"
  VERSION_ID="ev3124"
  HOME_URL="http://openwrt.org/"
  BUG_URL="http://bugs.openwrt.org/"
  SUPPORT_URL="http://forum.lede-project.org/"
  BUILD_ID="r7676-cddd7b4c77"
  LEDE_BOARD="ar71xx/generic"
  LEDE_ARCH="mips_24kc"
  LEDE_TAINTS="busybox override"
  LEDE_DEVICE_MANUFACTURER="OpenWrt"
  LEDE_DEVICE_MANUFACTURER_URL="http://openwrt.org/"
  LEDE_DEVICE_PRODUCT="Generic"
  LEDE_DEVICE_REVISION="EZEN-3X"
  LEDE_RELEASE="EZR23 EV3124 r7676-cddd7b4c77"

Kernel Version
4.9.152 #0 Wed Jan 30 12:21:02 2019 mips GNU/Linux

**Comment by Dvineone** [comment]
Seems building the binary using the below allows it to run. I tried the MIPS release on the router as well but it returned the below. I think GOMIPS=softfloat needs to be added but do not see a way yet to do this using GOX for just the MIPS build. 

GOOS=linux GOARCH=mips GOMIPS=softfloat go build ../cmd/* 

Test of both mips builds. The release from the github page fails. But the one using the above cross build flags works

<code>root@CellularRouter:/tmp# ./cake-autorate-linux-mips-v0.4</code>
Illegal instruction
<code>root@CellularRouter:/tmp# ./cake-autorate</code>
upload interface must be specified.

**Comment by notsure2** [comment]
I'll add soft float builds for arm and mips to the github actions script and re-run it.
------- Original Message -------

**Comment by Dvineone** [comment]
Awesome ty

**Comment by notsure2** [comment]
@Dvineone can you test the new release if one of them works on your router ?

**Comment by Dvineone** [comment]
@notsure2 
I can confirm the below does work on my router

[cake-autorate-linux-mips-softfloat-v0.4.2](https://github.com/notsure2/cake-autorate/releases/download/v0.4.2/cake-autorate-linux-mips-softfloat-v0.4.2)

**Comment by notsure2** [comment]
Thanks for the confirmation.
